name = "Farey"
uuid = "25ec4c3e-37ad-41bf-bc1b-e639ba3b65a6"
version = "1.0.0-DEV"
authors = ["Thomas Csizmadia <shadowfax.tdc86@gmail.com> and contributors"]

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
Chevie = "367f69f0-ca63-11e8-2372-438b29340c1b"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GroupsCore = "d5909c97-4eac-4ecc-a3dc-fdd0858a4120"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KnuthBendix = "c2604015-7b3d-4a30-8a26-9074551ec60a"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StarAlgebras = "0c0c59c1-dc5f-42e9-9a8b-b5dc384a6cd1"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnicodeFun = "1cfade01-22cf-5700-b092-accc4b62d6e1"

[compat]
Automa = "1.1.0"
Chevie = "0.1.12"
DataInterpolations = "8.9.0"
GLMakie = "0.13.8"
GroupsCore = "0.5.2"
JLD2 = "0.6.3"
KnuthBendix = "0.5.0"
Match = "2.4.1"
Revise = "3.13.2"
StarAlgebras = "0.3.0"
TOML = "1.0.3"
UnicodeFun = "0.4.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
