name = "Farey"
uuid = "25ec4c3e-37ad-41bf-bc1b-e639ba3b65a6"
authors = ["Thomas Csizmadia <shadowfax.tdc86@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
