name = "Farey"
uuid = "25ec4c3e-37ad-41bf-bc1b-e639ba3b65a6"
version = "1.0.0-DEV"
authors = ["Thomas Csizmadia <shadowfax.tdc86@gmail.com> and contributors"]

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
Chevie = "367f69f0-ca63-11e8-2372-438b29340c1b"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Automa = "1.1.0"
Chevie = "0.1.12"
Configurations = "0.17.6"
Match = "2.4.1"
Preferences = "1.5.1"
Revise = "3.13.2"
TOML = "1.0.3"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
